spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/kodilla_project?allowPublicKeyRetrieval=true&useSSL=false'
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update